export const API = {
  auth: {
    register: 'auth/register/',
    login: 'auth/login/',
    refresh: 'auth/token/refresh/',
    me: 'auth/users/me/',
    updateProfile: 'auth/users/update_profile/',
    users: 'auth/users/',
    user: (id: number) => `auth/users/${id}/`,
  },
  destinations: 'destinations/',
  destination: (id: number | string) => `destinations/${id}/`,
  packages: 'packages/',
  package: (id: number | string) => `packages/${id}/`,
  categories: 'packages/categories/',
  category: (id: number) => `packages/categories/${id}/`,
  hotels: 'hotels/',
  hotel: (id: number) => `hotels/${id}/`,
  flights: 'flights/',
  flight: (id: number) => `flights/${id}/`,
  activities: 'activities/',
  activity: (id: number) => `activities/${id}/`,
  bookings: 'bookings/',
  booking: (id: number) => `bookings/${id}/`,
  cancelBooking: (id: number) => `bookings/${id}/cancel/`,
  myBookings: 'bookings/my_bookings/',
  reviews: 'reviews/',
  review: (id: number) => `reviews/${id}/`,
  coupons: 'promotions/coupons/',
  wishlist: 'promotions/wishlists/',
  wishlistItem: (id: number) => `promotions/wishlists/${id}/`,
  inquiries: 'inquiries/',
  inquiry: (id: number) => `inquiries/${id}/`,
} as const
