export const API = {
  auth: {
    register: 'auth/register/',
    login: 'auth/login/',
    refresh: 'auth/token/refresh/',
    me: 'auth/users/me/',
    updateProfile: 'auth/users/update_profile/',
    changePassword: 'auth/change_password/',
    forgotPassword: 'auth/forgot_password/',
    resetPassword: 'auth/reset_password/',
    users: 'auth/users/',
    user: (id: number) => `auth/users/${id}/`,
  },
  destinations: 'destinations/',
  destination: (id: number | string) => `destinations/${id}/`,
  packages: 'packages/',
  package: (id: number | string) => `packages/${id}/`,
  categories: 'packages/categories/',
  category: (id: number) => `packages/categories/${id}/`,
  itinerary: (packageId: number | string) => `packages/${packageId}/itinerary/`,
  itineraryDay: (packageId: number | string, dayId: number) => `packages/${packageId}/itinerary/${dayId}/`,
  hotels: 'hotels/',
  hotel: (id: number) => `hotels/${id}/`,
  flights: 'flights/',
  flight: (id: number) => `flights/${id}/`,
  activities: 'activities/',
  activity: (id: number) => `activities/${id}/`,
  bookings: 'bookings/',
  booking: (id: number) => `bookings/${id}/`,
  cancelBooking: (id: number) => `bookings/${id}/cancel/`,
  refundBooking: (id: number) => `bookings/${id}/refund/`,
  myBookings: 'bookings/my_bookings/',
  createPaymentIntent: (id: number) => `bookings/${id}/create_payment_intent/`,
  confirmPayment: (id: number) => `bookings/${id}/confirm_payment/`,
  reviews: 'reviews/',
  review: (id: number) => `reviews/${id}/`,
  coupons: 'promotions/coupons/',
  coupon: (id: number) => `promotions/coupons/${id}/`,
  validateCoupon: 'promotions/coupons/validate/',
  wishlist: 'promotions/wishlists/',
  wishlistItem: (id: number) => `promotions/wishlists/${id}/`,
  inquiries: 'inquiries/',
  inquiry: (id: number) => `inquiries/${id}/`,
  adminMetrics: 'bookings/metrics/',
  notifications: 'auth/notifications/',
  markAllRead: 'auth/notifications/mark_all_read/',
  markRead: (id: number) => `auth/notifications/${id}/mark_read/`,
  whatsapp: {
    conversations: 'whatsapp/conversations/',
    messages: (id: number) => `whatsapp/conversations/${id}/messages/`,
    clearChat: (id: number) => `whatsapp/conversations/${id}/clear/`,
    send: 'whatsapp/send/',
    cancelMessage: (id: number) => `whatsapp/messages/${id}/cancel/`,
    campaigns: 'whatsapp/campaigns/',
    campaign: (id: number) => `whatsapp/campaigns/${id}/`,
    launchCampaign: (id: number) => `whatsapp/campaigns/${id}/launch/`,
    queueStats: 'whatsapp/queue/stats/',
    session: 'whatsapp/session/',
    sessionStart: 'whatsapp/session/start/',
    sessionQr: 'whatsapp/session/qr/',
    sessionLogout: 'whatsapp/session/logout/',
  },
} as const
