export const ROUTES = {
  home: '/',
  destinations: '/destinations',
  destination: (slug: string | number) => `/destinations/${slug}`,
  packages: '/packages',
  package: (slug: string | number) => `/packages/${slug}`,
  comparePackages: '/packages/compare',
  hotels: '/hotels',
  hotel: (id: number) => `/hotels/${id}`,
  flights: '/flights',
  activities: '/activities',
  activity: (id: number) => `/activities/${id}`,
  contact: '/contact',
  cotizar: '/cotizar',
  promotions: '/promotions',
  ofertas: '/ofertas',
  about: '/about',
  faq: '/faq',

  auth: {
    login: '/login',
    register: '/register',
    forgotPassword: '/forgot-password',
    resetPassword: '/reset-password',
  },

  customer: {
    dashboard: '/dashboard',
    profile: '/profile',
    bookings: '/bookings',
    booking: (id: number) => `/bookings/${id}`,
    newBooking: '/bookings/new',
    wishlist: '/wishlist',
    reviews: '/reviews',
    newReview: '/reviews/new',
    notifications: '/notifications',
  },

  admin: {
    dashboard: '/admin',
    destinations: '/admin/destinations',
    newDestination: '/admin/destinations/new',
    editDestination: (id: number) => `/admin/destinations/${id}`,
    packages: '/admin/packages',
    newPackage: '/admin/packages/new',
    editPackage: (id: number | string) => `/admin/packages/${id}`,
    categories: '/admin/categories',
    hotels: '/admin/hotels',
    newHotel: '/admin/hotels/new',
    editHotel: (id: number) => `/admin/hotels/${id}`,
    flights: '/admin/flights',
    newFlight: '/admin/flights/new',
    editFlight: (id: number) => `/admin/flights/${id}`,
    activities: '/admin/activities',
    newActivity: '/admin/activities/new',
    editActivity: (id: number) => `/admin/activities/${id}`,
    bookings: '/admin/bookings',
    booking: (id: number) => `/admin/bookings/${id}`,
    reviews: '/admin/reviews',
    inquiries: '/admin/inquiries',
    inquiry: (id: number) => `/admin/inquiries/${id}`,
    coupons: '/admin/coupons',
    payments: '/admin/payments',
    users: '/admin/users',
    whatsapp: '/admin/whatsapp',
    whatsappCampaigns: '/admin/whatsapp/campaigns',
  },
} as const
