export const ROUTES = {
  home: '/',
  destinations: '/destinations',
  destination: (slug: string | number) => `/destinations/${slug}`,
  packages: '/packages',
  package: (slug: string | number) => `/packages/${slug}`,
  hotels: '/hotels',
  hotel: (id: number) => `/hotels/${id}`,
  flights: '/flights',
  activities: '/activities',
  activity: (id: number) => `/activities/${id}`,
  contact: '/contact',
  promotions: '/promotions',

  auth: {
    login: '/login',
    register: '/register',
  },

  customer: {
    dashboard: '/dashboard',
    profile: '/profile',
    bookings: '/bookings',
    booking: (id: number) => `/bookings/${id}`,
    newBooking: '/bookings/new',
    wishlist: '/wishlist',
    newReview: '/reviews/new',
  },

  admin: {
    dashboard: '/admin',
    destinations: '/admin/destinations',
    newDestination: '/admin/destinations/new',
    editDestination: (id: number) => `/admin/destinations/${id}/edit`,
    packages: '/admin/packages',
    newPackage: '/admin/packages/new',
    editPackage: (id: number) => `/admin/packages/${id}/edit`,
    categories: '/admin/categories',
    hotels: '/admin/hotels',
    newHotel: '/admin/hotels/new',
    editHotel: (id: number) => `/admin/hotels/${id}/edit`,
    flights: '/admin/flights',
    newFlight: '/admin/flights/new',
    editFlight: (id: number) => `/admin/flights/${id}/edit`,
    activities: '/admin/activities',
    newActivity: '/admin/activities/new',
    editActivity: (id: number) => `/admin/activities/${id}/edit`,
    bookings: '/admin/bookings',
    booking: (id: number) => `/admin/bookings/${id}`,
    reviews: '/admin/reviews',
    inquiries: '/admin/inquiries',
    inquiry: (id: number) => `/admin/inquiries/${id}`,
    coupons: '/admin/coupons',
    users: '/admin/users',
  },
} as const
